name: FixValidationXUID
version: 1.0.1
api: 4.0.0
author: Gewinum
main: gewinum\xuidfix\FixValidation

commands:
  xuidfix:
    description: Fix XUID impersonation match problem
    permission: fixvalidationxuid.command

permissions:
  fixvalidationxuid.command:
    default: op
